# Generated by Django 5.2.17 on 2026-08-17 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('token_scope', models.CharField(choices=[('doctor', 'Per doctor'), ('clinic', 'Per clinic')], default='doctor', help_text='Whether walk-in numbers reset per doctor or shared clinic-wide.', max_length=16)),
                ('average_consult_minutes', models.PositiveSmallIntegerField(default=15)),
                ('notify_when_ahead', models.PositiveSmallIntegerField(default=2, help_text='Notify the patient when this many people are ahead.')),
                ('notifications_enabled', models.BooleanField(default=False)),
                ('appointment_priority_grace_minutes', models.PositiveSmallIntegerField(default=10, help_text='Checked-in appointments become due this many minutes before slot start.')),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('specialization', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('average_consult_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Override clinic average when set.', null=True)),
                ('queue_paused', models.BooleanField(default=False)),
                ('pause_reason', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='clinics.clinic')),
                ('staff_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
                'unique_together': {('clinic', 'display_name')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='clinics.clinic')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='clinics.doctor')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('clinic', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(help_text='0=Monday … 6=Sunday')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_minutes', models.PositiveSmallIntegerField(default=15)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='clinics.clinic')),
                ('doctor', models.ForeignKey(blank=True, help_text='Null means clinic-wide default hours.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='clinics.doctor')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='hours_end_after_start')],
            },
        ),
    ]
