# Generated by Django 5.2.17 on 2026-08-17 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('in_consult', 'In consult'), ('done', 'Done'), ('no_show', 'No-show'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('patient_name', models.CharField(max_length=120)),
                ('patient_phone', models.CharField(blank=True, max_length=32)),
                ('patient_email', models.EmailField(blank=True, max_length=254)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower is earlier. Reception may change this (audited).')),
                ('public_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notify_sent', models.BooleanField(default=False)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token', to='appointments.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='clinics.doctor')),
            ],
            options={
                'ordering': ['sort_order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='QueueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('issued', 'Issued'), ('called', 'Called'), ('in_consult', 'In consult'), ('done', 'Done'), ('no_show', 'No-show'), ('cancelled', 'Cancelled'), ('reordered', 'Reordered'), ('paused', 'Queue paused'), ('resumed', 'Queue resumed'), ('checked_in', 'Checked in')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_events', to='clinics.clinic')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinics.doctor')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='queues.token')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_sequences', to='clinics.clinic')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_sequences', to='clinics.doctor')),
            ],
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['clinic', 'service_date', 'status'], name='queues_toke_clinic__fd1109_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['public_key'], name='queues_toke_public__b4dd8e_idx'),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('clinic', 'doctor', 'service_date', 'number'), name='uniq_token_per_doctor_day'),
        ),
        migrations.AddConstraint(
            model_name='tokensequence',
            constraint=models.UniqueConstraint(condition=models.Q(('doctor__isnull', False)), fields=('clinic', 'doctor', 'service_date'), name='uniq_seq_doctor_day'),
        ),
        migrations.AddConstraint(
            model_name='tokensequence',
            constraint=models.UniqueConstraint(condition=models.Q(('doctor__isnull', True)), fields=('clinic', 'service_date'), name='uniq_seq_clinic_day'),
        ),
    ]
