# Generated by Django 5.2.17 on 2026-08-17 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('destination', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('success', models.BooleanField(default=True)),
                ('error', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='clinics.clinic')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='queues.token')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
